version: "3.7"

services:
    node-red:
        image: nodered/node-red:latest
        network_mode: "host"
        environment:
            - TZ=EST5EDT
        volumes:
            - ./data-clean:/data
        entrypoint: "npm run debug -- --userDir /data"
